/**
 * Markdown Report Generator
 *
 * Produces a clean, readable Markdown report from the analysis results.
 * Designed to render well in GitHub, VS Code, and other Markdown viewers.
 */

import { AnalysisReport, FailureAnalysis, RootCauseCategory, ROOT_CAUSE_CATEGORIES } from '../types.js';

/**
 * Generate a Markdown report string from the analysis results.
 */
export function generateMarkdownReport(report: AnalysisReport): string {
  const sections: string[] = [];

  // ─── Header ─────────────────────────────────────────────────────────
  sections.push('# 🔍 AI Failure Analysis Report');
  sections.push('');
  sections.push(`| | |`);
  sections.push(`|---|---|`);
  sections.push(`| **Report Generated** | ${formatTimestamp(report.timestamp)} |`);
  sections.push(`| **Input** | \`${report.inputPath}\` |`);
  sections.push(`| **Total Tests** | ${report.totalTests} |`);
  sections.push(`| **Failures Analyzed** | ${report.totalFailures} |`);
  sections.push(`| **Pass Rate** | ${((1 - report.totalFailures / report.totalTests) * 100).toFixed(1)}% |`);
  sections.push('');

  // ─── Summary by Category ───────────────────────────────────────────
  sections.push('---');
  sections.push('');
  sections.push('## 📊 Summary by Root Cause Category');
  sections.push('');

  const categoryCounts = countByCategory(report.analyses);
  const sortedCategories = Object.entries(categoryCounts)
    .sort(([, a], [, b]) => b - a);

  sections.push('| Category | Count | % of Failures | Confidence Breakdown |');
  sections.push('|:---------|:-----:|:-------------:|:---------------------|');

  for (const [category, count] of sortedCategories) {
    const pct = ((count / report.totalFailures) * 100).toFixed(1);
    const categoryAnalyses = report.analyses.filter((a) => a.category === category);
    const confidenceBreakdown = getConfidenceBreakdown(categoryAnalyses);
    const icon = getCategoryIcon(category as RootCauseCategory);
    sections.push(`| ${icon} ${category} | ${count} | ${pct}% | ${confidenceBreakdown} |`);
  }

  sections.push('');

  // Visual bar chart
  sections.push('### Distribution');
  sections.push('');
  for (const [category, count] of sortedCategories) {
    const bar = '█'.repeat(Math.max(1, Math.round((count / report.totalFailures) * 20)));
    const pct = ((count / report.totalFailures) * 100).toFixed(0);
    sections.push(`\`${padEnd(category, 28)}\` ${bar} ${count} (${pct}%)`);
  }
  sections.push('');

  // ─── Key Patterns ──────────────────────────────────────────────────
  if (sortedCategories.length > 0) {
    sections.push('---');
    sections.push('');
    sections.push('## 💡 Key Patterns');
    sections.push('');

    const topCategory = sortedCategories[0];
    if (topCategory[1] > 1) {
      sections.push(
        `> **${topCategory[1]} out of ${report.totalFailures}** failures are **${topCategory[0]}** — ` +
          `this is the dominant failure pattern and should be investigated first.`
      );
    }

    const highConfidence = report.analyses.filter((a) => a.confidence === 'High');
    if (highConfidence.length > 0) {
      sections.push('');
      sections.push(
        `> **${highConfidence.length}** failure(s) classified with **High confidence** — ` +
          `these are strong candidates for automated remediation.`
      );
    }

    sections.push('');
  }

  // ─── Detailed Analysis ─────────────────────────────────────────────
  sections.push('---');
  sections.push('');
  sections.push('## 📋 Detailed Analysis');
  sections.push('');

  // Group by category for easier scanning
  for (const [category] of sortedCategories) {
    const categoryAnalyses = report.analyses.filter((a) => a.category === category);
    const icon = getCategoryIcon(category as RootCauseCategory);

    sections.push(`### ${icon} ${category}`);
    sections.push('');

    for (const analysis of categoryAnalyses) {
      sections.push(formatAnalysisDetail(analysis));
      sections.push('');
    }
  }

  // ─── Token Usage & Cost ────────────────────────────────────────────
  sections.push('---');
  sections.push('');
  sections.push('## 💰 Token Usage & Cost');
  sections.push('');
  sections.push(`| Metric | Value |`);
  sections.push(`|--------|------:|`);
  sections.push(`| Input Tokens | ${report.tokenUsage.inputTokens.toLocaleString()} |`);
  sections.push(`| Output Tokens | ${report.tokenUsage.outputTokens.toLocaleString()} |`);
  sections.push(`| Total Tokens | ${(report.tokenUsage.inputTokens + report.tokenUsage.outputTokens).toLocaleString()} |`);
  sections.push(`| Estimated Cost | $${report.tokenUsage.estimatedCost.toFixed(4)} |`);
  sections.push('');
  sections.push('---');
  sections.push('');
  sections.push('*Generated by AI Failure Analysis Copilot (POC)*');

  return sections.join('\n');
}

// ─── Helpers ──────────────────────────────────────────────────────────────

function formatTimestamp(iso: string): string {
  const date = new Date(iso);
  return date.toLocaleString('en-US', {
    weekday: 'short',
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  });
}

function countByCategory(analyses: FailureAnalysis[]): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const a of analyses) {
    counts[a.category] = (counts[a.category] || 0) + 1;
  }
  return counts;
}

function getConfidenceBreakdown(analyses: FailureAnalysis[]): string {
  const high = analyses.filter((a) => a.confidence === 'High').length;
  const medium = analyses.filter((a) => a.confidence === 'Medium').length;
  const low = analyses.filter((a) => a.confidence === 'Low').length;
  const parts: string[] = [];
  if (high) parts.push(`🟢 ${high} High`);
  if (medium) parts.push(`🟡 ${medium} Med`);
  if (low) parts.push(`🔴 ${low} Low`);
  return parts.join(', ');
}

function getCategoryIcon(category: RootCauseCategory): string {
  const icons: Record<RootCauseCategory, string> = {
    'Locator/Selector Issue': '🎯',
    'Timing/Sync Issue': '⏱️',
    'Test Data Issue': '📦',
    'Environment/Infra Issue': '🌐',
    'Application Bug': '🐛',
    'Test Script Bug': '📝',
    'Unknown/Needs Manual Review': '❓',
  };
  return icons[category] || '❓';
}

function formatAnalysisDetail(analysis: FailureAnalysis): string {
  const confBadge =
    analysis.confidence === 'High' ? '🟢 High' :
    analysis.confidence === 'Medium' ? '🟡 Medium' :
    '🔴 Low';

  const lines: string[] = [];
  lines.push(`#### ${analysis.testName}`);
  lines.push('');
  lines.push(`**Confidence:** ${confBadge}`);
  lines.push('');
  lines.push(`**Explanation:** ${analysis.explanation}`);
  lines.push('');
  lines.push(`**Suggested Action:** ${analysis.suggestedAction}`);
  lines.push('');
  if (analysis.codeFix) {
    lines.push('**Proposed Code Fix:**');
    lines.push('');
    lines.push('```diff');
    lines.push(analysis.codeFix.unifiedDiff);
    lines.push('```');
    lines.push('');
  }
  lines.push('<details>');
  lines.push('<summary>Relevant Log Excerpt</summary>');
  lines.push('');
  lines.push('```');
  lines.push(analysis.relevantLogExcerpt);
  lines.push('```');
  lines.push('</details>');

  return lines.join('\n');
}

function padEnd(str: string, len: number): string {
  return str + ' '.repeat(Math.max(0, len - str.length));
}
